"""Project Generator — creates real MVP projects using Claude Code CLI.

Uses `claude` CLI on the server to generate complete projects:
- Analyzes hackathon requirements
- Generates full project code in a directory
- Creates README, demo page, etc.
"""
from __future__ import annotations

import json
import logging
import os
import re
import subprocess
from pathlib import Path

logger = logging.getLogger("aizavod.project_generator")

PROJECTS_DIR = Path("/opt/aizavod/hackathon_projects")


def _run_claude(prompt: str, cwd: str | None = None, timeout: int = 300,
                allow_tools: bool = False) -> str:
    """Run Claude Code CLI with a prompt and return output."""
    cmd = ["claude", "-p", prompt]
    if allow_tools:
        cmd.append("--dangerously-skip-permissions")
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=cwd,
        )
        output = result.stdout.strip()
        if result.returncode != 0 and not output:
            output = result.stderr.strip()
        return output
    except subprocess.TimeoutExpired:
        return "ERROR: Claude CLI timeout"
    except Exception as e:
        return f"ERROR: {e}"


async def generate_project(
    hackathon_title: str,
    hackathon_description: str,
    requirements: str,
    technologies_required: list[str] | None = None,
    project_type: str = "web_app",
) -> dict:
    """Generate a complete MVP project for a hackathon using Claude Code.

    Returns dict with project info and file paths.
    """
    # Step 1: Ask Claude to plan the project
    plan_prompt = f"""You are a hackathon expert. Design a winning MVP project.

HACKATHON: {hackathon_title}
DESCRIPTION: {hackathon_description[:3000]}
REQUIREMENTS: {requirements}
{f'REQUIRED TECH: {", ".join(technologies_required)}' if technologies_required else ''}
TYPE: {project_type}

Respond ONLY in JSON (no markdown, no explanation):
{{
    "project_name": "kebab-case-name",
    "display_name": "Display Name",
    "tagline": "One line (max 80 chars)",
    "description": "2-3 sentences",
    "tech_stack": ["tech1", "tech2"],
    "key_features": ["feature1", "feature2", "feature3"],
    "demo_strategy": "How to demo impressively"
}}"""

    plan_text = _run_claude(plan_prompt, timeout=120)
    plan = _extract_json(plan_text)

    if not plan:
        logger.error("Failed to parse project plan from Claude")
        return {"success": False, "error": "Failed to generate plan"}

    project_name = plan.get("project_name", "hackathon-project")
    project_dir = PROJECTS_DIR / project_name
    project_dir.mkdir(parents=True, exist_ok=True)

    # Step 2: Let Claude Code generate the entire project
    build_prompt = f"""Create a complete, working hackathon project in the current directory.

PROJECT: {plan.get('display_name', project_name)}
TAGLINE: {plan.get('tagline', '')}
DESCRIPTION: {plan.get('description', '')}
TECH STACK: {', '.join(plan.get('tech_stack', []))}
KEY FEATURES: {', '.join(plan.get('key_features', []))}

CRITICAL RULES:
1. Create ALL files needed for a working project
2. MUST have index.html as entry point (for GitHub Pages demo)
3. Use Tailwind CSS via CDN for styling — make it look polished and modern
4. No build step required — everything must work as static files or single-page app
5. Include complete, working JavaScript — no placeholders, no TODOs
6. If API calls needed, use free public APIs or mock data
7. Make it visually impressive — good UI/UX wins hackathons
8. Create a README.md with project description, features, tech stack, setup instructions
9. All code must be production-quality

Create the files now."""

    logger.info("Running Claude Code to generate project in %s", project_dir)
    build_output = _run_claude(build_prompt, cwd=str(project_dir), timeout=600,
                               allow_tools=True)
    logger.info("Claude Code output: %s", build_output[:500])

    # Check what files were created
    generated_files = []
    for fpath in project_dir.rglob("*"):
        if fpath.is_file() and not str(fpath).startswith("."):
            generated_files.append(str(fpath.relative_to(project_dir)))

    if not generated_files:
        logger.error("No files generated")
        return {"success": False, "error": "No files generated by Claude"}

    # Step 3: Generate DevPost description
    devpost_prompt = f"""Generate DevPost submission description for this hackathon project.

PROJECT: {plan.get('display_name', project_name)}
TAGLINE: {plan.get('tagline', '')}
HACKATHON: {hackathon_title}
TECH STACK: {', '.join(plan.get('tech_stack', []))}
DESCRIPTION: {plan.get('description', '')}
FEATURES: {', '.join(plan.get('key_features', []))}

Respond ONLY in JSON (no markdown):
{{
    "inspiration": "2-3 paragraphs about what inspired this",
    "what_it_does": "2-3 paragraphs about what it does",
    "how_we_built_it": "2-3 paragraphs about technical implementation",
    "challenges_we_ran_into": "1-2 paragraphs about challenges",
    "accomplishments": "1-2 paragraphs about what we're proud of",
    "what_we_learned": "1-2 paragraphs about learnings",
    "whats_next": "1-2 paragraphs about future plans"
}}"""

    desc_text = _run_claude(devpost_prompt, timeout=120)
    devpost_desc = _extract_json(desc_text) or {}

    return {
        "success": True,
        "project_dir": str(project_dir),
        "project_name": project_name,
        "display_name": plan.get("display_name", project_name),
        "tagline": plan.get("tagline", ""),
        "files": generated_files,
        "technologies": plan.get("tech_stack", []),
        "devpost_description": devpost_desc,
        "plan": plan,
    }


async def generate_screenshots(
    project_dir: str,
    demo_url: str = "",
) -> list[str]:
    """Generate screenshots of the project for DevPost submission."""
    screenshots = []
    pdir = Path(project_dir)
    (pdir / "screenshots").mkdir(exist_ok=True)

    from services.devpost_automation import get_devpost
    devpost = get_devpost()

    if demo_url:
        path = str(pdir / "screenshots" / "demo_main.png")
        await devpost.take_screenshot(demo_url, path)
        screenshots.append(path)
    else:
        # Screenshot local HTML files
        html_files = list(pdir.glob("*.html")) + list(pdir.glob("**/*.html"))
        seen = set()
        for html_file in html_files[:3]:
            if html_file.name in seen:
                continue
            seen.add(html_file.name)
            path = str(pdir / "screenshots" / f"{html_file.stem}.png")
            await devpost.take_screenshot(f"file://{html_file}", path)
            screenshots.append(path)

    return screenshots


def _extract_json(text: str) -> dict | list | None:
    """Extract JSON from Claude output."""
    # Clean markdown code blocks
    text = re.sub(r"^```(?:json)?\s*\n?", "", text, flags=re.MULTILINE)
    text = re.sub(r"\n?```\s*$", "", text, flags=re.MULTILINE)
    text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try finding JSON in text
    for pattern in [
        re.compile(r"```json\s*\n(.*?)\n```", re.DOTALL),
        re.compile(r"(\{[^{}]*(?:\{[^{}]*\}[^{}]*)*\})", re.DOTALL),
        re.compile(r"(\[.*?\])", re.DOTALL),
    ]:
        match = pattern.search(text)
        if match:
            try:
                return json.loads(match.group(1))
            except json.JSONDecodeError:
                continue
    return None
